<?php

/**
 * Implements hook_install()
 */
function behat_test_install() {
  $storage = \Drupal::service('behat_test.config.storage.install');
  $config_names = array(
    'core.entity_form_display.user.user.default',
    'core.entity_view_display.user.user.default',
  );

  foreach ($config_names as $config_name) {
    $data = $storage->read($config_name);
    $config = \Drupal::configFactory()->getEditable($config_name);
    $config->setData($data);
    $config->save();
  }
}
