<?php

/**
 * @file
 * Install hooks for the behat_test module.
 */

/**
 * Implements hook_install().
 */
function behat_test_install() {
  // Attach the editorial workflow to the article content type so that computed
  // base fields like 'moderation_state' are available for testing.
  $workflow = \Drupal\workflows\Entity\Workflow::load('editorial');
  $workflow->getTypePlugin()->addEntityTypeAndBundle('node', 'article');
  $workflow->save();

  $storage = \Drupal::service('behat_test.config.storage.install');

  // Override Standard profile's user settings with our own.
  $config_names = [
    'core.entity_form_mode.user.register',
    'core.entity_form_display.user.user.default',
    'core.entity_view_display.user.user.default',
    'core.entity_view_display.user.user.compact',
    'core.entity_view_mode.user.compact',
    'core.entity_view_mode.user.full',
  ];

  foreach ($config_names as $config_name) {
    $data = $storage->read($config_name);
    \Drupal::configFactory()->getEditable($config_name)->setData($data)->save();
  }
}
