parameters:
  drupal.driver.drush.class: Drupal\Driver\DrushDriver

  # Random generator.
  drupal.random.class: Drupal\Component\Utility\Random

services:
  drupal.driver.random:
    class: %drupal.random.class%
  drupal.driver.drush:
    class: %drupal.driver.drush.class%
    arguments:
      - %drupal.driver.drush.alias%
      - %drupal.driver.drush.root%
      - %drupal.driver.drush.binary%
      - "@drupal.driver.random"
    tags:
      - { name: drupal.driver, alias: drush }
