name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '8.4'
      DRUPAL_VERSION: '11'
      DOCKER_USER_ID: '1001'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start Docker containers
        run: docker compose up -d

      - name: Install Composer dependencies
        run: docker compose exec -T php composer install

      - name: Validate composer.json
        run: docker compose exec -T php composer validate --no-interaction

      - name: Check composer.json is normalized
        run: docker compose exec -T php composer normalize --dry-run

      - name: Run linting
        run: docker compose exec -T php composer lint

  tests:
    name: PHP ${{ matrix.php_version }}, Drupal ${{ matrix.drupal_version }}, Deps ${{ matrix.deps }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php_version: '8.2'
            drupal_version: '10'
            deps: 'normal'
          - php_version: '8.2'
            drupal_version: '10'
            deps: 'lowest'
          - php_version: '8.3'
            drupal_version: '10'
            deps: 'normal'
          - php_version: '8.3'
            drupal_version: '10'
            deps: 'lowest'
          - php_version: '8.3'
            drupal_version: '11'
            deps: 'normal'
          - php_version: '8.3'
            drupal_version: '11'
            deps: 'lowest'
          - php_version: '8.4'
            drupal_version: '10'
            deps: 'normal'
          - php_version: '8.4'
            drupal_version: '10'
            deps: 'lowest'
          - php_version: '8.4'
            drupal_version: '11'
            deps: 'normal'
          - php_version: '8.4'
            drupal_version: '11'
            deps: 'lowest'

    env:
      PHP_VERSION: ${{ matrix.php_version }}
      DRUPAL_VERSION: ${{ matrix.drupal_version }}
      DOCKER_USER_ID: '1001'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Start Docker containers
        run: docker compose up -d

      - name: Add Drupal core dependency
        run: docker compose exec -u ${DOCKER_USER_ID} -T php composer require --no-interaction --dev --no-update drupal/core:^${DRUPAL_VERSION} drupal/core-composer-scaffold:^${DRUPAL_VERSION}

      - name: Install Composer dependencies
        run: |
          if [[ "${{ matrix.deps }}" == "lowest" ]]; then
            docker compose exec -T php composer update --prefer-lowest --prefer-stable
          else
            docker compose exec -T php composer install
          fi

      - name: Run PHPSpec tests
        run: docker compose exec -T php composer test-phpspec

      - name: Provision Drupal site
        run: docker compose exec -T php ./vendor/bin/drush --yes --root=drupal site-install --db-url=mysql://drupal:drupal@db/drupal --debug

      - name: Copy test fixtures
        run: docker compose exec -T php cp -r fixtures/drupal/modules/behat_test drupal/modules

      - name: Adjust Drupal configurations
        run: |
          docker compose exec -T php ./vendor/bin/drush --yes --root=drupal pmu page_cache,big_pipe
          docker compose exec -T php ./vendor/bin/drush --yes --root=drupal en behat_test
          docker compose exec -u ${DOCKER_USER_ID} -T php vendor/bin/drush cset core.date_format.olivero_medium pattern 'j F, Y'
          docker compose exec -u ${DOCKER_USER_ID} -T php vendor/bin/drush cset automated_cron.settings interval 0
          docker compose exec -u ${DOCKER_USER_ID} -T php vendor/bin/drush cset user.settings register visitors

      - name: Run Behat tests
        run: docker compose exec -T php composer test-bdd
